# Generated by Django 5.2.6 on 2025-11-05 21:58

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_carrito_itemcarrito_alter_detallepedido_subtotal_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="producto",
            name="invernadero",
        ),
        migrations.AddField(
            model_name="producto",
            name="descripcion_corta",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="producto",
            name="tips",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="carrito",
            name="cliente",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="core.cliente"
            ),
        ),
        migrations.AlterField(
            model_name="producto",
            name="descripcion",
            field=models.TextField(blank=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="producto",
            name="imagen",
            field=models.ImageField(upload_to="productos/"),
        ),
        migrations.AlterField(
            model_name="producto",
            name="precio",
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
