# Generated by Django 5.2.6 on 2025-11-12 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_remove_producto_invernadero_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="itemcarrito",
            unique_together={("carrito", "producto")},
        ),
    ]
