# Generated by Django 5.2.6 on 2025-11-12 18:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_alter_itemcarrito_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="pedido",
            name="direccion_envio",
            field=models.CharField(
                blank=True,
                help_text="Dirección usada en este pedido (puede ser distinta al perfil).",
                max_length=200,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="pedido",
            name="tipo_entrega",
            field=models.CharField(
                choices=[
                    ("Despacho", "Despacho a domicilio"),
                    ("Retiro", "Retiro en tienda"),
                ],
                default="Despacho",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="producto",
            name="invernadero",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="productos",
                to="core.invernadero",
            ),
            preserve_default=False,
        ),
    ]
