# Generated by Django 5.2.6 on 2025-11-12 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_pedido_direccion_envio_pedido_tipo_entrega_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="producto",
            name="categoria",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="producto",
            name="cuidados",
            field=models.TextField(
                blank=True,
                help_text="Recomendaciones adicionales o curiosidades",
                null=True,
            ),
        ),
    ]
