# Generated by Django 5.2.6 on 2025-11-12 21:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_producto_categoria_producto_cuidados"),
    ]

    operations = [
        migrations.CreateModel(
            name="Etiqueta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name="producto",
            name="altura_aproximada",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Altura promedio en cm",
                max_digits=5,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="producto",
            name="curiosidades",
            field=models.TextField(
                blank=True, help_text="Datos interesantes o históricos", null=True
            ),
        ),
        migrations.AddField(
            model_name="producto",
            name="disponible",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="producto",
            name="fecha_actualizacion",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="producto",
            name="luz_recomendada",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="producto",
            name="nombre_cientifico",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name="producto",
            name="riego",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="producto",
            name="sku",
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="producto",
            name="temperatura_optima",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="producto",
            name="cuidados",
            field=models.TextField(
                blank=True,
                help_text="Recomendaciones específicas de cuidado",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="producto",
            name="imagen",
            field=models.ImageField(blank=True, null=True, upload_to="productos/"),
        ),
        migrations.CreateModel(
            name="ProductoEtiqueta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "etiqueta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.etiqueta"
                    ),
                ),
                (
                    "producto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="etiquetas",
                        to="core.producto",
                    ),
                ),
            ],
            options={
                "unique_together": {("producto", "etiqueta")},
            },
        ),
    ]
