# Generated by Django 5.2.6 on 2025-11-13 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0013_etiqueta_producto_altura_aproximada_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="pedido",
            name="metodo_pago",
            field=models.CharField(default="Transbank", max_length=50),
        ),
        migrations.AddField(
            model_name="pedido",
            name="paypal_email",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="pedido",
            name="paypal_order_id",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="pedido",
            name="paypal_payer_id",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="pedido",
            name="paypal_response",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="pedido",
            name="paypal_status",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="pedido",
            name="transbank_autorizacion",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="pedido",
            name="transbank_response",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="pedido",
            name="transbank_tarjeta_tipo",
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name="pedido",
            name="transbank_tarjeta_ultimos4",
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AddField(
            model_name="pedido",
            name="transbank_token",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="pedido",
            name="direccion_envio",
            field=models.CharField(
                blank=True,
                help_text="Dirección utilizada en este pedido.",
                max_length=200,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="pedido",
            name="estado",
            field=models.CharField(
                choices=[
                    ("P", "Pendiente"),
                    ("EP", "Esperando Pago"),
                    ("PA", "Pagado"),
                    ("R", "Rechazado"),
                    ("C", "Cancelado"),
                ],
                default="P",
                max_length=2,
            ),
        ),
    ]
